project_name: bitset
before:
  hooks:
    - go mod tidy
snapshot:
  name_template: "{{ .Tag }}"
builds:
  - skip: true
release:
  draft: false
  replace_existing_draft: true
  prerelease: false
  mode: append
  header: |
    ## Release {{ .Tag }} ({{ .Date }})
    
    See [CHANGELOG.md](CHANGELOG.md) for details.
changelog:
  disable: true
